### PR TITLE
issues#110 - Popovers with same id in Coral.Actionbar.

### PR DESCRIPTION
**Pull request by indra2gurjar**
## Description - 
These changes fix the id duplication of popover when an action is moved to/from more popover.

## Related Issue 
https://github.com/adobe/coral-spectrum/issues/110

## Motivation and Context  --> 
These changes fix the id duplication of popover when an action is moved to/from more popover.

## How Has This Been Tested?  --> 
Test Added.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by icaraps** [comment]
Does the last example "With action menu" from Action Bar still work ? Can you open the popover ?

```html

        <coral-actionbar id="switchBar1">
          <coral-actionbar-item>
            <button is="coral-button" variant="quiet" icon="copy">Copy</button>
          </coral-actionbar-item>
          <coral-actionbar-item>
            <button is="coral-button" variant="quiet" icon="globe">Publish</button>
          </coral-actionbar-item>
          <coral-actionbar-item>
            <button is="coral-button" variant="quiet" icon="globeRemove">Unpublish</button>
          </coral-actionbar-item>
          <coral-actionbar-item>
            <button class="popover-button" is="coral-button" icon="search" title="Delete">Open Popover</button>
            <coral-popover target=".popover-button" placement="bottom">
              <coral-buttonlist>
                <button is="coral-buttonlist-item" icon="add">Add</button>
                <button is="coral-buttonlist-item" icon="move">Move</button>
                <button is="coral-buttonlist-item" disabled="">Delete</button>
              </coral-buttonlist>
            </coral-popover>
          </coral-actionbar-item>
          <coral-actionbar-item>
            <button is="coral-button" variant="quiet" icon="copy">Copy</button>
          </coral-actionbar-item>
          <coral-actionbar-item>
            <button is="coral-button" variant="quiet" icon="globe">Publish</button>
          </coral-actionbar-item>
          <coral-actionbar-item>
            <button is="coral-button" variant="quiet" icon="globeRemove">Unpublish</button>
          </coral-actionbar-item>
        </coral-actionbar>
```

**Comment by indra2gurjar** [comment]
@icaraps  >Does the last example "With action menu" from Action Bar still work ? Can you open the popover ?

How can check that? I mean how can I run the examples with my changes?

**Comment by icaraps** [comment]
You can do `cd coral-component-actionbar && gulp` then open localhost:9001

**Comment by indra2gurjar** [comment]
@icaraps  >Does the last example "With action menu" from Action Bar still work ? Can you open the popover ?

Yes and No.
Yes, in normal scenario when the action is visible in the list.
No, in scenario when the action is not visible and becomes visible in more popover. But this is is the case without the changes in this PR. let me fix that as well.

Thanks for reviewing.

**Comment by indra2gurjar** [comment]
@icaraps  Fixed the target issue.
The last example now works fine for both the cases.
1. When popover button is inside more popover.
2. When it is outside more popover. 

Could you please help in reviewing...

**Comment by indra2gurjar** [comment]
@icaraps  Gentle reminder.

**Pull request merged**
