### PR TITLE
SITES-10934: Color alone is used to convey information.

### PR DESCRIPTION
**Pull request by stefan-dragomir**
https://jira.corp.adobe.com/browse/SITES-10934

### CODE REVIEW

**Review by ens84646 — APPROVED** [review]

**Review by petcud — APPROVED** [review]
Please fix the curly braces.
For the complexity warning, if you cannot simplify the complexity, and it's code that wasn't introduced by you, it might generate a code smell report but should be fine to merge.

**Comment by ens84646** [comment]
> Please fix the curly braces. For the complexity warning, if you cannot simplify the complexity, and it's code that wasn't introduced by you, it might generate a code smell report but should be fine to merge.

@petcud check warnings not related to the actual change, should we resolve this reports for every PR created as long as it were not generated by this PR?

**Comment by mariang-ens** [comment]
Opened a new PR with some fixes to the curly braces [here](https://github.com/adobe/coral-spectrum/pull/336)

**Comment by TeodorEns** [comment]
Please close this as this implementation was moved to https://github.com/adobe/coral-spectrum/pull/336

**Comment by StoianLucian** [comment]
implementation was moved to https://github.com/adobe/coral-spectrum/pull/336

**Pull request closed without merging**
