### PR TITLE
CUI-7370 [Accessibility] Coral.Autocomplete: Use WAI-ARIA 1.2 Combobox design pattern

### PR DESCRIPTION
**Pull request by majornista**
## Description
Refactor Coral.Autocomplete to implement WAI-ARIA 1.2 Combobox design pattern where the `input` has `role="combobox"` rather than the container.

## Related Issue
Per: https://jira.corp.adobe.com/browse/CQ-4292426
and https://jira.corp.adobe.com/browse/CUI-7370

## How Has This Been Tested?
Tested with VoiceOver on macOS and NVDA on Windows.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by majornista** [comment]
Please review: @adobre90, @adobe/coral-spectrum, @icaraps, @mohiaror

**Comment by icaraps** [comment]
Can you please add/modify tests ?

**Comment by majornista** [comment]
Could I get a review: @CezCz, @adobe/coral-spectrum?

**Comment by icaraps** [comment]
@majornista I'm ok to merge if you add tests. Also any particular reason to use coral-dialog in the example ? Would it be possible to use a non coral container in this case ? The example won't work as standalone ie `cd coral-component-autocomplete && gulp` because dialog is not imported.

**Comment by majornista** [comment]
Thanks for the tip about testing just one component rather than the full repository. I can remove the dialog example. I was just trying to verify that Esc key will close the autocomplete list box but not the containing dialog.

**Comment by majornista** [comment]
@icaraps and @adobe/coral-spectrum Please verify with tests added, and dialog example removed.

**Pull request merged**
