### PR TITLE
fix : updating AEM icon to marketing subcloud-icon

### PR DESCRIPTION
**Pull request by ShreeSub**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by ShreeSub** [comment]
attaching the new lcon as suggested by branding team
marketing_cloud_appicon_noshadow_256
@icaraps please review

**Comment by ShreeSub** [comment]
@CezCz can you please review and help in merging?
cc: @icaraps

**Comment by Pareesh** [comment]
Hello @ShreeSub ,
Please follow the commit message convention mentioned by @CezCz here : https://cq-dev.slack.com/archives/C8B81NL8J/p1601387495004800

**Comment by ShreeSub** [comment]
I have updated the commit message, please review @Pareesh @CezCz

**Review by Pareesh — APPROVED** [review]

**Pull request merged**
