### PR TITLE
fix: updating spectrum product logos according new branding changes

### PR DESCRIPTION
**Pull request by ShreeSub**
## Description

The product logos have been updated according to the new branding rules
## Related Issue

 https://jira.corp.adobe.com/browse/GRANITE-33028 

## Motivation and Context

Please find attached  the zip file containing the updated product logos
## How Has This Been Tested?

[ticket 209 (1).zip](https://github.com/adobe/coral-spectrum/files/6426399/ticket.209.1.zip)
Airtable ticket: https://airtable.com/shrneeQowbccTkCL5/tblOpDwAMEzLDf6mC/rec4zH4WBbSEQPwgp 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by ShreeSub** [comment]
@Pareesh @indra2gurjar please review

**Comment by Pareesh** [comment]
@ShreeSub please update all necessary details in PR description

**Comment by ShreeSub** [comment]
> @ShreeSub please update all necessary details in PR description

@Pareesh I have added the airtable ticket and JIRA issue also the recommended icons.

**Review by majornista — APPROVED** [review]

**Comment by Pareesh** [comment]
Hello @ShreeSub ,
Please update `type of changes` and `checklist` checkbox.

**Review by Pareesh — APPROVED** [review]

**Pull request merged**
