### PR TITLE
fix(ASSETS-6921): Hours and Minutes validation error label not available

### PR DESCRIPTION
**Pull request by ionelc-ensemble**
https://jira.corp.adobe.com/browse/ASSETS-6921
https://jira.corp.adobe.com/browse/ASSETS-6920
https://jira.corp.adobe.com/browse/ASSETS-6852

## Description
Added an error label to coral clock that is displayed whenever the hours and/or minutes inputs are invalid.

## How Has This Been Tested?

Tested manually  & with screen reader

## Screenshots (if appropriate):
Screen Shot 2022-08-17 at 19 08 27

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by RitwikSrivastava** [comment]
@Pareesh to review.

**Comment by ionelc-ensemble** [comment]
@RitwikSrivastava to fix 'e' adding invalid markers on the input but not adding the invalid attributes, I added an event listener on the clock to remove 'e' whenever it is typed.
Here's a short recording of current behavior:

https://user-images.githubusercontent.com/74657799/185425220-c363e7fd-adcc-4bf2-9773-9ab87c06fa73.mov

**Comment by ionelc-ensemble** [comment]
New recording after fixing the input to prevent typing 'e' altogether:

https://user-images.githubusercontent.com/74657799/186120963-89e95426-5397-4cb7-bf48-af88e0c98882.mov

**Comment by RitwikSrivastava** [comment]
> New recording after fixing the input to prevent typing 'e' altogether:
> 
>  Screen.Recording.2022-08-23.at.10.38.51.mov

Looks OK to me. @Pareesh Can you also review ?

**Review by Pareesh — APPROVED** [review]
Please add test cases related to it and change the document.querySelector to this.querySelector.

LGTM

**Comment by Pareesh** [comment]
Hi @ionelc-ensemble ,
Please check the build https://github.com/adobe/coral-spectrum/runs/8092608603?check_suite_focus=true ,  seems some axe related failure for coral-clock-error-label.

**Pull request merged**
