### PR TITLE
CQ-4291308 Port to Spectrum: Column View: the checkboxes in the grid all lack programmatic names (AEM Sites)

### PR DESCRIPTION
**Pull request by majornista**
## Description
Port accessibility updates from Coral3 ColumnView

Improve WAI-ARIA design pattern to ensure that

1. An element can always receive keyboard focus even after
initialization.
2. non-contiguous elements can be selected when selectionMode is
multiselect
3. State of item is announced by assistive technology on select or
deselect.
4. Command/Control + A and Shift+Command/Control + A can be used to
select or deselect all.
5. Esc deselects all.
6. Navigating using arrow keys sets focus on appropriate item.
7. Add unit tests for keyboard interaction and accessibility
8. When a document item is active, the preview column is added as
description for activeItem.

## Related Issue
https://jira.corp.adobe.com/browse/CQ-4274574,
https://jira.corp.adobe.com/browse/CQ-4291308
https://jira.corp.adobe.com/browse/CQ-4291309

## Motivation and Context
Improve ColumnView accessibility for keyboard and screen reader users.

## How Has This Been Tested?
Unit test, and extensive manual testing.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by majornista** [comment]
@adobe/coral-spectrum, @icaraps, @kozmaadrian, @martinischeery, @gknobloch

**Comment by majornista** [comment]
Could I get a review? @adobe/coral-spectrum, @icaraps, @kozmaadrian, @martinischeery, @gknobloch

**Comment by pfauchere** [comment]
@icaraps  @CezCz @kozmaadrian  could you please help with the review? We would like to have it shipped in the coming days

**Comment by martinischeery** [comment]
Ping @Pareesh @indra2gurjar

**Pull request merged**
