### PR TITLE
CUI-7418 [A11y][NVDA] Coral.Multiform Provide keyboard accessible way to reorder items

### PR DESCRIPTION
**Pull request by majornista**
## Description
Using NVDA, it should be possible to activate the "move" button on a Multiform item using Enter/Space, and use ArrowUp/ArrowDown/Home/End to reorder the item.

Pressing Enter or Space (or blurring the item) should complete the move.

Pressing Esc should cancel the move operation, restoring the item to its original location.

## Related Issue
[CUI-7418](https://jira.corp.adobe.com/browse/CUI-7418)
[CQ-4281120](https://jira.corp.adobe.com/browse/CQ-4281120)

## Motivation and Context
MSFT 5006164 - [Screen Reader-Adobe AEM-Core component show case-Teaser-Link & Actions]: There is no alternative way provided for the screen reader users to drag and drop the 'Move UpDown' button in 'Link & Actions' dialog.

Workaround is for the user to add the items in the correct order and delete as necessary.

## How Has This Been Tested?
Tested with NVDA and VoiceOver using examples in Coral-Spectrum.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by majornista** [comment]
@icaraps

**Comment by anagarwa** [comment]
@CezCz

**Comment by anagarwa** [comment]
ESC key should stop propagation.

**Comment by icaraps** [comment]
Did you take into consideration that Multifields can be nested ? Would that be a problem in this case ?

**Comment by majornista** [comment]
@icaraps nested multifields work in the example document.

**Comment by anagarwa** [comment]
@icaraps  can this be merged ?

**Pull request merged**
