### PR TITLE
fix(Accessability): Add button role to table header interactive element

### PR DESCRIPTION
**Pull request by StoianLucian**
Ticket: [SITES-10962](https://jira.corp.adobe.com/browse/SITES-10962)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by StoianLucian** [comment]
The failed accessibility tests show that the aria-sort attribute is not allowed
image

My question is that if the tickets requirements are correct?

**Comment by Pareesh** [comment]
Hi @StoianLucian ,
I think the 'th' element of table should have aria-sort and role as "columnheader". 

The coral-table-headercell-content should be role button, I guess that would correct the accessibility.

Since the impact of this change is quite large spread, please add a null check to avoid same regression in future.

Thank you

**Comment by StoianLucian** [comment]
Hello @Pareesh  even if i target the  coral-table-headercell-content i still get the same test fails regarding aria sort attribute and surely removing the aria-sort attribute is not a good ideea
Could it be maybe the requirement of the ticket is not correct?


image

**Comment by majornista** [comment]
> Hello @Pareesh even if i target the coral-table-headercell-content i still get the same test fails regarding aria sort attribute and surely removing the aria-sort attribute is not a good ideea And according to https://www.digitala11y.com/columnheader-role/ role columnheader the supported properties are
> 
> image
> 
> Could it be maybe the requirement of the ticket is not correct?
> 
> image

There seem to be some strange choices going on when the table header is `sticky`, like adding `role="presentation"` to the `th[is="coral-table-headercell"]` and moving `role="columnheader"` to the `coral-table-headercell-content`, which is in part why you are seeing axe error when you then set `role="button"` on `coral-table-headercell-content`, which overrides the `role="columnheader"`. 

@StoianLucian and @Pareesh, do you mind if I commit some suggested changes to this PR?

**Comment by StoianLucian** [comment]
hello @majornista, Please do!

**Comment by StoianLucian** [comment]
Hi @Pareesh the changes are done

**Review by hparwani2 — APPROVED** [review]

**Review by Pareesh — APPROVED** [review]

**Pull request merged**
