### PR TITLE
CUI-7345 [Accessibility] Icon alt text should not default to a non-localized icon name.

### PR DESCRIPTION
**Pull request by majornista**
## Description

The original intent of using the icon name as alternative text for accessibility, was to localize the icon name to some meaningful string, so that if no aria-label were provided to an icon-only button, the button would still be identified in a meaningful way to assistive technology. The current implementation simply uses the non-localized name for the Icon, which populates the interface with strings like ''Chevron Right" or "Chevron Down", which aren't helpful, and are problematic without proper translation.

It is better to let icon-only buttons without an aria-label, remain unlabelled so that automated testing tools have an opportunity to identify the missing label.

I've also laid the foundation for i18n by creating a `translations.js` file with variant-stripped icon names and suggested strings for things like Chevron Up/Down/Left/Right. An icon can be explicitly set to use the default string, which should be localized by setting `Coral.Icon.autoAriaLabel = true`.

## Related Issue

- [CUI-7345](https://jira.corp.adobe.com/browse/CUI-7345)
- [CUI-4769](https://jira.corp.adobe.com/browse/CUI-4769)
- [CUI-4770](https://jira.corp.adobe.com/browse/CUI-4770)

## Motivation and Context

The original intent of using the icon name as alternative text for accessibility, was to localize the icon name to some meaningful string, so that if no aria-label were provided to an icon-only button, the button would still be identified in a meaningful way to assistive technology. The current implementation simply uses the non-localized name for the Icon, which populates the interface with strings like ''Chevron Right" or "Chevron Down", which aren't helpful, and are problematic without proper translation.

## How Has This Been Tested?
Unit tests, and example page has been updated

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by majornista** [comment]
@CezCz and @icaraps Could I get a review?

**Comment by CezCz** [comment]
@majornista 
I think we need to fix the examples page, either add autoarialabel=on to generated buttons or provide contextual labels as axe is quite unhappy.

**Comment by majornista** [comment]
> @majornista
> I think we need to fix the examples page, either add autoarialabel=on to generated buttons or provide contextual labels as axe is quite unhappy.

Yep, and that's just example pages.

**Comment by majornista** [comment]
@CezCz I've updated the examples to fix `gulp axe` errors in example pages.

**Comment by icaraps** [comment]
Thanks a lot @majornista 🥇

**Pull request merged**
