### PR TITLE
Adseth CQ-4273031:Updating attributes in underlined elements in readOnly mode for select and datepicker.

### PR DESCRIPTION
**Pull request by Gabiesfat**
For the bug CQ-4273031 we were needed to migrate attribute "disabled" to "readOnly" in supertype form fields (/libs/granite/ui/components/coral/foundation/form/field). This was done to make all the inheriting fields of form field accessible  based on following conditions:

1.            Able to make field displayable but not editable (read-only).
2.            User should be able to copy the text written underneath.
3.            User should be able to access the field with click(mouse) and tab(keyboard).

This was achieved by adding a new attribute "readOnly" in /libs/granite/ui/components/coral/foundation/form/field and leveraging it but apparently following components still didn't honour the attribute so to fix them we had to create the PRs [0] and [1]. And to honour them in coral-spectrum I created this PR.
1. coralui-component-datepicker
2. coralui-component-select

[0] https://git.corp.adobe.com/Coral/coralui-component-datepicker/pull/72/files
[1] https://git.corp.adobe.com/Coral/coralui-component-select/pull/104/files

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

As in coral spectrum PRs redundant whitespaces are getting injested so I added the exact link of code changes for easy reference.

coral-component-datepicker/src/scripts/Datepicker.js 

1. https://github.com/adobe/coral-spectrum/pull/68/files#diff-acaf0592ec5664bc5dae8cde518870d6L464-R464
2. https://github.com/adobe/coral-spectrum/pull/68/files#diff-acaf0592ec5664bc5dae8cde518870d6L515-R518

coral-component-datepicker/src/tests/test.Datepicker.js 

1. https://github.com/adobe/coral-spectrum/pull/68/files#diff-62f3fd1bc96606e09b7016415768c45dL303-L310

coral-component-select/src/scripts/Select.js

1. https://github.com/adobe/coral-spectrum/pull/68/files#diff-34540f7f47417594812fbcc3b50f3e33L429-L432
2. https://github.com/adobe/coral-spectrum/pull/68/files#diff-34540f7f47417594812fbcc3b50f3e33L482-L485
3. https://github.com/adobe/coral-spectrum/pull/68/files#diff-34540f7f47417594812fbcc3b50f3e33L1001-L1002
4. https://github.com/adobe/coral-spectrum/pull/68/files#diff-34540f7f47417594812fbcc3b50f3e33L1037-L1038

coral-component-select/src/tests/test.Select.js

1. https://github.com/adobe/coral-spectrum/pull/68/files#diff-7f38e98a680c4b36aa72c375e86c0694L1455-R1493

### CODE REVIEW

**Comment by icaraps** [comment]
@Gabiesfat please sign the CLA first. What are the changes ? It's hard to read as the diff is huge.

**Comment by Gabiesfat** [comment]
> @Gabiesfat please sign the CLA first. What are the changes ? It's hard to read as the diff is huge.

Signed the Adobe CLA and elaborated the description of changes.

**Comment by icaraps** [comment]
@Gabiesfat Thank you. Can you please point me to the lines that are actually changing the code ?

**Comment by icaraps** [comment]
@Gabiesfat similar to https://github.com/adobe/coral-spectrum/pull/60#issue-403668619 where the PR mentions all actual code changes via links

**Comment by Gabiesfat** [comment]
> @Gabiesfat similar to [#60 (comment)](https://github.com/adobe/coral-spectrum/pull/60#issue-403668619) where the PR mentions all actual code changes via links

Done, thanks Stephan for the suggestion.

**Comment by icaraps** [comment]
I have reverted this change as the adminconsole team reported the Select in readonly state did allow selection after this commit which is a regression.

**Pull request merged**
