### PR TITLE
fix(SITES-2874 Accessibility) - Visual list is not marked up as list.

### PR DESCRIPTION
**Pull request by StoianLucian**
Ticket: [SITES-2874](https://jira.corp.adobe.com/browse/SITES-2874)

Added role list and listitem to the required elements

### CODE REVIEW

**Comment by StoianLucian** [comment]
after applying the change, axe devTools can't identify the problem that appears in the failing build
image_720

**Comment by StoianLucian** [comment]
Capture

**Review by petcud — APPROVED** [review]
Please fix the curly braces.
For the complexity warning, if you cannot simplify the complexity, and it's code that wasn't introduced by you, it might generate a code smell report but should be fine to merge.

**Review by petcud — CHANGES_REQUESTED** [review]
try the aria role 'list' instead of the 'listitem'

**Comment by ens84646** [comment]
> Please fix the curly braces. For the complexity warning, if you cannot simplify the complexity, and it's code that wasn't introduced by you, it might generate a code smell report but should be fine to merge.

@petcud check warnings not related to the actual change, should we resolve this reports for every PR created as long as it were not generated by this PR?

**Comment by StoianLucian** [comment]
Hi @petcud the role "list" is only to be use for the wrapper of the list and the role "listitem" is to be used for the each element from inside the wrapper as suggested in the ticket and in the accessibility guides https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listitem_role

**Review by cbogdan0707 — APPROVED** [review]

**Comment by StoianLucian** [comment]
@Pareesh is there anything else we should do regarding this ticket? If not could you merge it?

**Pull request closed without merging**
