### PR TITLE
fix(ASSETS-6851): The selected state of the action button does not have a sufficient contrast ratio

### PR DESCRIPTION
**Pull request by TudorSMR**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Pareesh** [comment]
Hi @TudorSMR ,
Please change the title based on coral commit convention for automatic release process to trigger.

Thank you

**Comment by TudorSMR** [comment]
@Pareesh Done.
Thanks!

**Comment by Pareesh** [comment]
Hi @TudorSMR ,
This `rgb(158, 158, 158)` seems to be quite a used value, Please create a var in var.css and then use it. Also change this https://github.com/adobe/coral-spectrum/commit/093fb74d5c9354c6ca72afcea6e0adc0705a97e8 to var.

Create two different variable name fro border and background color.
Thank you

**Review by Pareesh — APPROVED** [review]

**Comment by Pareesh** [comment]
Hi @TudorSMR ,
For css changes, try to attach a screenshot of before and after, it would be easier to review. 

Thank you

**Comment by TudorSMR** [comment]
Hi @Pareesh ,
I've updated the css to use vars. Here are the before and after screenshots.
Before:
image
After:
image

**Review by Pareesh — APPROVED** [review]

**Pull request merged**
