### PR TITLE
CUI-7341 : Accessibility improvements for ActionBar

### PR DESCRIPTION
**Pull request by indra2gurjar**
The changes fixes 2 issues :
1. ActionBar items which has selectable elements at 2nd level e.g. coral-fileupload are not selectable.
2. Offscreen ActionBar items are accessible.

## Description
1. Added code to find selectable elements in an ActionBar item if no selectable element found at first level.
2. Added code to set aria-hidden="true" to hide offscreen items from being read by screen-reader.

## How Has This Been Tested?
1. Manually tested with keyboard navigation.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by icaraps** [comment]
aXe reported a11y issues `ARIA hidden element must not contain focusable elements` see https://api.travis-ci.com/v3/job/283770285/log.txt

**Comment by indra2gurjar** [comment]
@majornista  aXe reported a11y issues ARIA hidden element must not contain focusable elements. Should we hide offscreen items by "display:none"? WDYT?

**Comment by majornista** [comment]
> @majornista aXe reported a11y issues 'ARIA hidden element must not contain focusable elements.' Should we hide offscreen items by "display:none"? WDYT?


I think the better approach would be to use `visibility: hidden` so that the offscreen items can still be measured.

**Comment by indra2gurjar** [comment]
@majornista  Added visibility:hidden . Please review.

**Comment by indra2gurjar** [comment]
@icaraps @majornista  Can we merge this PR? All the checks are passing and suggestions are incorporated.

**Comment by icaraps** [comment]
Can you still go through items with the keyboard if an item is hidden ? e.g tab into the actionbar then use left-right arrow. 
Also does it work if the hidden item is not the first one ?

**Comment by indra2gurjar** [comment]
>>Can you still go through items with the keyboard if an item is hidden ? e.g tab into the actionbar then use left-right arrow.
Yes
>>Also does it work if the hidden item is not the first one ?
Yes

You can verify at http://igurjar:4502/assets.html/content/dam , select first folder 'test_sss'

**Comment by indra2gurjar** [comment]
@majornista  Opened CUI-7352 for ESC key issue.

**Comment by majornista** [comment]
@indra2gurjar and @icaraps I think that both the overlay mixin and the granite view handle the Esc key in the capture phase, so I'm not sure we can `stopPropagation` within Coral to prevent the granite view from deselecting all items and closing the action bar. This may be an issue that has to be handled in granite.

**Pull request merged**
